export const reports = [
  {
    id: 0,
    reportsName: "Site reports",
    details: [
      {
        reportName: "Site Report A",
        content: "Site Report Content A",
        creator: "Darlene Robertson",
        department: "Design",
        dateCreated: "30.10.2023",
        dateUpdated: "31.10.2023",
        purpose: "Site Analysis",
      },
    ],
  },
  {
    id: 1,
    reportsName: "Travel reports Content Based on 12",
    details: [
      {
        reportName: "Travel Report B Content Base on 19",
        content: "Travel Report Content B",
        creator: "Alex Johnson",
        department: "Operations",
        dateCreated: "01.11.2023",
        dateUpdated: "02.11.2023",
        purpose: "Travel Expense Tracking",
      },
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
    ],
  },
  {
    id: 2,
    reportsName: "Budget reports",
    details: [
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
    ],
  },
  {
    id: 3,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 4,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 5,
    reportsName: "Site reports",
    details: [
      {
        reportName: "Site Report A",
        content: "Site Report Content A",
        creator: "Darlene Robertson",
        department: "Design",
        dateCreated: "30.10.2023",
        dateUpdated: "31.10.2023",
        purpose: "Site Analysis",
      },
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
    ],
  },
  {
    id: 6,
    reportsName: "Travel reports",
    details: [
      {
        reportName: "Travel Report B",
        content: "Travel Report Content B",
        creator: "Alex Johnson",
        department: "Operations",
        dateCreated: "01.11.2023",
        dateUpdated: "02.11.2023",
        purpose: "Travel Expense Tracking",
      },
    ],
  },
  {
    id: 7,
    reportsName: "Budget reports",
    details: [
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
    ],
  },
  {
    id: 8,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 9,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 10,
    reportsName: "Site reports",
    details: [
      {
        reportName: "Site Report A",
        content: "Site Report Content A",
        creator: "Darlene Robertson",
        department: "Design",
        dateCreated: "30.10.2023",
        dateUpdated: "31.10.2023",
        purpose: "Site Analysis",
      },
    ],
  },
  {
    id: 11,
    reportsName: "Travel reports",
    details: [
      {
        reportName: "Travel Report B",
        content: "Travel Report Content B",
        creator: "Alex Johnson",
        department: "Operations",
        dateCreated: "01.11.2023",
        dateUpdated: "02.11.2023",
        purpose: "Travel Expense Tracking",
      },
    ],
  },
  {
    id: 12,
    reportsName: "Budget reports",
    details: [
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
    ],
  },
  {
    id: 13,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 14,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 15,
    reportsName: "Site reports",
    details: [
      {
        reportName: "Site Report A",
        content: "Site Report Content A",
        creator: "Darlene Robertson",
        department: "Design",
        dateCreated: "30.10.2023",
        dateUpdated: "31.10.2023",
        purpose: "Site Analysis",
      },
    ],
  },
  {
    id: 16,
    reportsName: "Travel reports",
    details: [
      {
        reportName: "Travel Report B",
        content: "Travel Report Content B",
        creator: "Alex Johnson",
        department: "Operations",
        dateCreated: "01.11.2023",
        dateUpdated: "02.11.2023",
        purpose: "Travel Expense Tracking",
      },
    ],
  },
  {
    id: 17,
    reportsName: "Budget reports",
    details: [
      {
        reportName: "Budget Report C",
        content: "Budget Report Content C",
        creator: "Elena Gilbert",
        department: "Finance",
        dateCreated: "03.11.2023",
        dateUpdated: "04.11.2023",
        purpose: "Annual Budget Planning",
      },
    ],
  },
  {
    id: 18,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 19,
    reportsName: "Marketing reports",
    details: [
      {
        reportName: "Marketing Report D",
        content: "Marketing Report Content D",
        creator: "John Smith",
        department: "Marketing",
        dateCreated: "05.11.2023",
        dateUpdated: "06.11.2023",
        purpose: "Market Analysis",
      },
    ],
  },
  {
    id: 20,
    reportsName: "Final reports",
    details: [
      {
        reportName: "Final Report T",
        content: "Final Report Content T",
        creator: "Darlene Robertson",
        department: "Design",
        dateCreated: "30.10.2023",
        dateUpdated: "31.10.2023",
        purpose: "Project Closure",
      },
    ],
  },
];
